package com.hrms.rest.persistence.entity;
// Generated Apr 9, 2024, 8:01:41 AM by Hibernate Tools 6.0.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.time.LocalDateTime;

/**
 * Absence generated by hbm2java
 */
@Entity
@Table(name="absence"
    ,catalog="hrms_db"
)
public class Absence  implements java.io.Serializable {


     private Integer leaveId;
     private Employee employee;
     private LocalDateTime leaveStartDate;
     private LocalDateTime leaveEndDate;
     private String leaveType;
     private String leaveStatus;

    public Absence() {
    }

    public Absence(Employee employee, LocalDateTime leaveStartDate, LocalDateTime leaveEndDate, String leaveType, String leaveStatus) {
       this.employee = employee;
       this.leaveStartDate = leaveStartDate;
       this.leaveEndDate = leaveEndDate;
       this.leaveType = leaveType;
       this.leaveStatus = leaveStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="leave_id", unique=true, nullable=false)
    public Integer getLeaveId() {
        return this.leaveId;
    }
    
    public void setLeaveId(Integer leaveId) {
        this.leaveId = leaveId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="leave_start_date", length=19)
    public LocalDateTime getLeaveStartDate() {
        return this.leaveStartDate;
    }
    
    public void setLeaveStartDate(LocalDateTime leaveStartDate) {
        this.leaveStartDate = leaveStartDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="leave_end_date", length=19)
    public LocalDateTime getLeaveEndDate() {
        return this.leaveEndDate;
    }
    
    public void setLeaveEndDate(LocalDateTime leaveEndDate) {
        this.leaveEndDate = leaveEndDate;
    }

    
    @Column(name="leave_type", length=9)
    public String getLeaveType() {
        return this.leaveType;
    }
    
    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }

    
    @Column(name="leave_status", length=8)
    public String getLeaveStatus() {
        return this.leaveStatus;
    }
    
    public void setLeaveStatus(String leaveStatus) {
        this.leaveStatus = leaveStatus;
    }




}


